release:
  prerelease: false

builds:
  - binary: dist/github-pr-approval
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.buildTime={{.Date}}`.

dockers:
  - dockerfile: Dockerfile
    use: docker
    # todo: on 1.0 remove 'v' prefix
    image_templates:
      - "unikraft/concourse-github-pr-approval-resource:latest"
      - "unikraft/concourse-github-pr-approval-resource:{{ .Tag }}"
      - "unikraft/concourse-github-pr-approval-resource:v{{ .Major }}"
      - "unikraft/concourse-github-pr-approval-resource:v{{ .Major }}.{{ .Minor }}"
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - cmd/
      - api/
      - actions/
      - assets/
      - Makefile


